## Podstawy NumPy i NumPy Arrays

W tej lekcji wprowadzę Cię do biblioteki NumPy, która jest fundamentalnym narzędziem do obliczeń naukowych w Pythonie. NumPy, czyli Numerical Python, oferuje wszechstronne wsparcie dla wielowymiarowych tablic i macierzy, a także szeroki zakres funkcji matematycznych. NumPy to biblioteka Pythona, która umożliwia pracę z wielowymiarowymi tablicami (arrays) oraz dostarcza narzędzia do przeprowadzania operacji matematycznych na tych tablicach. W kontekście Pandas, NumPy arrays są podstawą dla struktury DataFrame.

### Tworzenie NumPy Arrays

In [13]:
import numpy as np

data = [1, 2, 3, 4]
array = np.array(data)

print(array)
print(data)



[1 2 3 4]
[1, 2, 3, 4]


In [15]:
array_arange = np.arange(10)
array_arange_2 = np.arange(10, 20, 2)

print(array_arange)
print(array_arange_2)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]


### Operacje na NumPy Arrays

In [17]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

print(array_1 + array_2)
print(array_1 * 2)
print(array_1 ** 2)

[5 7 9]
[2 4 6]
[1 4 9]


In [20]:
array = np.array([10, 20, 30, 40, 50])
print(array[1:4])

[20 30 40]


In [26]:
array = np.arange(12)
array_reshaped = array.reshape((3, 4))

print(array)
print(array_reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Homogeniczność

NumPy arrays są homogeniczne, co oznacza, że wszystkie elementy muszą być tego samego typu.

In [27]:
my_list = [1, 2, 'a', 4, 5]
my_array = np.array(my_list)
print(my_list)
print(my_array)

[1, 2, 'a', 4, 5]
['1' '2' 'a' '4' '5']


### Listy vs NumPy Arrays

- NumPy arrays są znacznie bardziej wydajne pod względem pamięci i szybkości niż listy Pythona. Operacje na NumPy arrays są wykonywane szybciej dzięki implementacji w języku C.
- NumPy arrays wspierają elementarne operacje matematyczne bezpośrednio na całych tablicach, co jest bardziej intuicyjne i szybsze niż iterowanie przez listy.
- NumPy oferuje szeroki wachlarz funkcji matematycznych, statystycznych i operacji algebry liniowej, które nie są dostępne dla list.